README.md, src/Command/ParallelCommand.php, src/UI/ProgressBarRenderer.php, src/UI/VerboseRenderer.php
Use case for this is as follows:
We have a lot of functional tests that even with fastest run about ~10 minutes on our CI system. Sometimes developers will look at the log right away to see if the tests are passing and they should fix something, but sometimes they will only look when the build is already over. Using this option among with `-vv` would help us to both see failures in realtime and do not display errors twice in a final log.
=> Add --no-errors-summary option

src/Command/ParallelCommand.php, src/Process/Processes.php, src/Process/Report.php, src/UI/VerboseRenderer.php, tests/Process/ProcessesTest.php
To achieve this I also had to rework waiting for the last processes, so now the progressbar rendering in the end of the queue is done when every process is terminated, not just once when they all are. This fixes a weird behaviour in verbose log that in the end of the queue there was always `$totalParallelProcesses` less log lines then total, even if just one process is running.
=> Display time it took the process to run in Verbose mode

src/Command/ParallelCommand.php
This fixes newly introduced bug where the last entry is not displayed in the verbose log when running with `-p1`
=> Clean up processes before waiting

adapters/Doctrine/DBAL/ConnectionFactory.php
SQLite does not have `dbname` parameter (in fact, SQLite databases do not have names - it's always one database per 1 file). So, if useing sqlite, you should
```
doctrine:
dbal:
driver:   pdo_sqlite
path:     "%kernel.cache_dir%/__DBNAME__.db"
```
Where `__DBNAME__` will be replaced with ENV_TEST_CHANNEL_READABLE.value
=> Change path instead of dbName for SQLite driver

README.md
Locking on `dev-master` is a bad practice. We should advocate locking on stable tag.
=> Advocate stable tag in README

README.md
Due to incorrect `variables_order` setting I faced problems with `unknown command` errors. This update describes he problem and solution.
=> Update README with unknown command solution

README.md, src/Process/EnvCommandCreator.php, src/Process/ProcessFactory.php, tests/Process/ProcessFactoryTest.php, tests/Process/ProcessesManagerTest.php
As suggested by @Seldaek we're passing `null` to Symfony's Process component, which results in useing current ENV variables. Just before creating the process we use `putenv` to inject fastest variables. This solution does not depend on `php.ini` settings.
=> Use putenv to set fastest enviroment variables.

README.md, src/Process/EnvCommandCreator.php, src/Process/ProcessFactory.php, tests/Process/ProcessFactoryTest.php, tests/Process/ProcessesManagerTest.php
Reverts liuggio/fastest#58
Seems like this causes an unexpected breaking of rerun functionality. Reverting changes until analysing the problem.
=> Revert "Use putenv to set fastest enviroment variables."

.travis.yml, README.md, composer.json, src/Process/EnvCommandCreator.php, tests/Process/ProcessFactoryTest.php, tests/Process/ProcessesManagerTest.php
This PR started of with adding symfony3 compability, however a few other fixes are included:
* require allows symfony3 components
* bumped minor version in doc and composer.json
* replaced `$_ENV` with `getenv('PATH')` and adjusted tests
* added PHP 7.0 to travis config (allowed failure)
=> Add symfony3 compability

src/Process/EnvCommandCreator.php, tests/Process/ProcessFactoryTest.php
It seems removeing the `$_ENV` was premature, as some other enviroment variables are needed sometimes.
Eg. symfony2.8, I can't connect to database - same command: `app/console doctrine:database:drop` 
* executed directly - works
* executed via fastest - does not work
* executed via fastest with `$_ENV` and `variables_order=EGCPS` (in `php.ini`) - works again
=> Full enviroment table fallback

README.md
- Fix typos "its" → "it's"
- Capitalization
- Filename formatting
- Use same version "~1.3" when installing with composer require or the composer.json file
- Symfony2 is now known as Symfony
=> Improvements in README.md:

.travis.yml, README.md
Add Composer cache in Travis CI's cache
Remove PHP 7.0 from allowed failures
Use "composer require …" instead of "sed …"
=> Fixes #72: Improve Travis CI tests:

.travis.yml, composer.json, src/Command/ParallelCommand.php, src/Queue/CreateTestsQueueFromPhpUnitXML.php, tests/Queue/CreateTestsQueueFromPhpUnitXMLTest.php, tests/Queue/Fixture/phpunit.xml.dist, tests/Queue/ReadFromInputAndPushIntoTheQueueTest.php
SF 3.x compatibility due to the deprecated progress helper (Had to bump Symfony version therefore)
I also added a way to fix issues with handling of PHPUnit configuration files.
Tickets:
- fixes #26
=> Phpunit Loader

adapters/Doctrine/DBAL/ConnectionFactory.php
If you work on a master/slave connection, the `dbname` parameter does not exists and is set in the `master` key. 
Same for the `path` stored in `master` key and each `slave`
=> manage sqlite master slave database path

src/Process/ProcessorCounter.php
| New feature?  | yes
| Fixed tickets | #1
This PR add the compatibility Windows to retrieve automatically the number of logical processors.
=> Add the Windows compatibility for the processor counter

src/Process/ProcessFactory.php
| Bug fix?      | yes
| Fixed tickets | #24
On Windows, there is a bug to pass the environment variable into process (see https://php.net/manual/en/function.proc-open.php#117912).
Symfony Process fix this bug since the 3.2 version, but you must call the method `Process::inheritEnvironmentVariables()` to pass the environment variables into the process (see symfony/symfony#19053).
Since the 3.3 version, this method is deprecated because all environement variables are passed into the process if no custom variables are used (see symfony/symfony#21470).
However, Fastest use the custom environment …
=> Fix Windows compatibility

adapters/Behat/ListFeaturesExtension/Console/Processor/ListFeaturesProcessor.php, adapters/Behat/features/listFeatures.feature, adapters/Behat/features/testResources/features/firstfeature.feature.resource, adapters/Behat2/ListFeaturesExtension/Console/Processor/ListFeaturesProcessor.php, adapters/Behat2/features/listFeatures.feature, adapters/Behat2/features/testResources/features/firstfeature.feature.resource
Hello,
I noticed that the `ListFeaturesExtension`, when used with `list-scenarios` consider `Scenario Outline` as one scenario but in our case they are the longest scenarios so it could be nice to split them as separated scenarios.
=> Improve Behat list scenarios for Outline scenarios

.gitignore, src/Command/ParallelCommand.php, src/UI/VerboseRenderer.php
Before:
```
wunder@code-2017-VirtualBox:~/PhpstormProjects/fastest$ find tests/ -name "*Test.php" | php fastest -v
- 10 shuffled test classes into the queue.
- Will be consumed by 4 parallel Processes.
1/10    ✔       67 ms           tests/Process/ProcessorCounterTest.php
2/10    ✔       90 ms           tests/Queue/CreateTestsQueueFromPhpUnitXMLTest.php
3/10    ✔       68 ms           tests/Queue/Infrastructure/InMemoryQueueFactoryTest.php
4/10    ✔       134 ms          tests/Process/ProcessesTest.php
5/10    ✔       150 ms          tests/Queue/ReadFromInputAndPushIntoTheQueueTest.php
6/10    ✔       81 ms           tests/Environment/FastestEnvironmentTest.php
7/10    ✔       84 ms           tests/Process/ProcessFactoryTest.php
8/10    ✔       71 ms …
```
=> Final results as in human readable

src/Process/EnvCommandCreator.php, src/Process/ProcessFactory.php, src/Process/Processes.php, tests/Process/ProcessFactoryTest.php
| Bug fix?      | yes
| Fixed tickets | ~
With Symfony 4 Flex, it is now recommended to configure the environment variables in the phpunit XML configuration. Phpunit does not overwrite the existing environment variables with the default variables set in the XML configuration.
It works fine using Phpunit directly, however this is not the case using Fastest on linux (and therefore also Docker), but works for Windows. The PR #98 already made it possible to correct a problem of environment variable for Windows, but in this case, the problem is also present for all the platforms.
We could set in the …
=> Fix the overriding of env variables for the phpunit config

composer.json
| Fixed tickets | ~
The current branch alias of the `master` branch must be `1.5` and not `1.4`.
=> Update the composer branch alias

src/Queue/CreateTestsQueueFromPhpUnitXML.php, tests/Queue/Fixture/tests/bootstrap.php
| Fixed tickets | ~
The Phpunit bootstrap file is not loaded, and it's problematic with a custom bootstrap file in global installation.
This PR add the possibility to use a custom bootstrap file defined in the Phpunit configuration file.
=> Load the phpunit bootstrap file

README.md, src/Process/ProcessFactory.php
| Fixed tickets | ~
The Symfony's team strongly recommend in Symfony 4 Flex should not add in the Phpunit dependencies in our projects, even in dev. So, it is recommended to install Phpunit globally. However, Fastest is not able to work in global mode.
This PR allow to install/use the Fastest in global mode with Phpunit.
=> Allow to install Fastest in global mode

.travis.yml, composer.json, src/Process/EnvCommandCreator.php, tests/Process/ProcessFactoryTest.php
| Bug fix?      | yes
| Fixed tickets | #116
To follow the discussion of the issue #116, I confirm that the problem stems from a different behavior between versions of the Symfony Process component. In the `< 3.2` versions, each value of the environment variables is converted to binary, whereas in the `>= 3.2` versions, the values are directly added without conversion. You can see the difference in the code:
- [Symfony Process v4.0](https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Process/Process.php#L1083)
- [Symfony Process …
=> Fix behavior variations of different versions of symfony process in tests

src/Process/ProcessFactory.php
| New feature?  | yes
| Fixed tickets | #99
This PR allow to use Phpunit installed in the `./vendor/bin` directory in addition of the directories:
- `./bin`
- `~/.composer/vendor/bin` (unix)
- `%APPDATA%\Composer\vendor\bin` (windows)
- Or all Phpunit binary defined in the `PATH` variables
=> Find phpunit in vendor bin directory

.travis.yml, src/Process/ProcessorCounter.php, src/Queue/CreateTestsQueueFromPhpUnitXML.php, tests/Process/ProcessorCounterTest.php
It was renamed from `PHPUnit\Util\Fileloader` to `PHPUnit\Util\FileLoader` in https://github.com/sebastianbergmann/phpunit/commit/3a9494be34135e5d42964ec7f5f17605e736a2c7#diff-7862e6eec2d5923e62d57728b79a0480
=> Fix renamed file loader in phpunit

.travis.yml, composer.json
In two months PHP 7.1 will go in "end of life" status https://www.php.net/supported-versions.php
As no sooner release seems to be planned and I really don't know when I will have time again to check this project, I've decided to bump PHP version.
=> Bumped PHP min version

composer.json
Symfony 2.8 will be "end of life" in a month https://symfony.com/roadmap/2.8
Moreover I've bumped version 4 minor version to 2
=> Bumped symfony version

.gitignore, .travis.yml, tests/Environment/FastestEnvironmentTest.php, tests/Process/ProcessFactoryTest.php, tests/Process/ProcessesManagerTest.php, tests/Process/ProcessesTest.php, tests/Process/ProcessorCounterTest.php, tests/Queue/CreateTestsQueueFromPhpUnitXMLTest.php, tests/Queue/CreateTestsQueueFromSTDINTest.php, tests/Queue/Infrastructure/InMemoryQueueFactoryTest.php, tests/Queue/ReadFromInputAndPushIntoTheQueueTest.php
- Remove `php7.4-snapshot` version test and using `php-7.4` version instead on Travis CI build.
- According to the [PHPUnit fixtures reference](https://phpunit.de/manual/7.0/en/fixtures.html), the `setUp` method is `protected`, not `public`.
=> Test improvement

composer.json, phpstan.neon, src/Process/Processes.php, src/Queue/CreateTestsQueueFromPhpUnitXML.php
PHPStan version fixated in composer.json
=> Fixated PHPStan version

composer.json
Given [this](https://github.com/doctrine/collections/blob/2.1.x/UPGRADE.md#bc-breaking-changes), seems no harm to include major version 2 as an alternative dependency.
I only noticed this as one of my projects wanted to upgrade to `doctrine/collections:^2.0` but couldn't because `liuggio/fastest` depends exclusively on major version 1.
=> Allow doctrine/collections:^2.0 as alternative dependency

composer.json, src/Queue/TestsQueue.php
Follow-up to the discussion in https://github.com/liuggio/fastest/pull/187
I've decided to use https://github.com/symfony/deprecation-contracts , because it provides a unified way to do deprecations. Also it's already a transitive dependency of this package:
```
symfony/config               v6.2.7     requires symfony/deprecation-contracts (^2.1|^3) 
symfony/console              v6.2.7     requires symfony/deprecation-contracts (^2.1|^3) 
symfony/dependency-injection v6.2.7     requires symfony/deprecation-contracts (^2.1|^3) 
```
=> Doctrine collections compatibility

composer.json
I upgrade dependencies to symfony/* 7.0
"symfony/console": "^4.4|^5.0|^6.0|^7.0",
"symfony/stopwatch": "^4.4|^5.0|^6.0|^7.0",
"symfony/process": "^4.4.35|^5.0|^6.0|^7.0",
=> Upgrade dependencies to symfony/* 7.0
